
server:
  port: 8989
spring:
  redis:
    host: 39.108.106.34
    port: 6379
    # 密码 没有则可以不填
    password: redis
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
debug: true
